const tooltips = {
  proMode: "Deep system cleanup and performance boost.",
  internet: "Improves speed, stability, and online gaming latency.",
  registry: "Safe tweaks for smoother, faster Windows.",
  disk: "Frees space and improves drive performance.",
  gpu: "Boosts FPS and graphics performance automatically.",
  windowsGaming: "Enables gaming features and reduces background load.",
  display: "Sets your monitor to maximum refresh rate.",
  browser: "Speeds up website loading and browsing.",
  launchers: "Faster downloads and smoother launcher performance.",
  wifi: "Stronger, more stable wireless connection.",
  dns: "Uses the fastest DNS for your area.",
  debloat: "Disables unnecessary apps for better performance.",
  drivers: "Fixes driver issues and improves stability.",
  intro3d: "Cinematic intro for a premium experience.",
  cleanup: "Removes temp files, cache, and system junk for a fresh start.",
  performance: "Boosts system speed and responsiveness with advanced tweaks.",
  finalSweep: "Final clean-up pass to consolidate all optimizations.",
  restore: "Creates a system restore point before making changes.",
  fps: "Optimizes graphics, GPU scheduling, and system for higher FPS.",
  security: "Hardens Windows security settings against threats.",
  winfix: "Scans and repairs system files with SFC and DISM.",
  deep: "Advanced toggles for startup, telemetry, background apps, and more.",
  master: "Full system repair & speedup — app installs, tweaks, and advanced configuration.",
  allInOne: "Runs Clean & Clear, Performance Boost, and Final Sweep sequentially.",
  repair: "Full Windows diagnostic suite — SFC, DISM, CHKDSK, BCD boot check, network reset, memory diagnostics, and system stability checks."
};
